#!/bin/bash

set -euo pipefail

_base_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
source "$_base_dir/vendor/github.com/reconquest/import.bash/import.bash"

import:use github.com/reconquest/test-runner.bash
import:use github.com/reconquest/go-test.bash

:init() {
    go-test:set-output-dir "$(readlink -f .)"
    go-test:build orgalorg-bottlebreaker
}

:cleanup() {
    go-test:merge-coverage
}

trap :cleanup EXIT

:init 2>/dev/null

test-runner:run "${@}"
